update gitpush

diff --git a/commands/gitpush b/commands/gitpush
--- a/commands/gitpush
+++ b/commands/gitpush
@@ -4,9 +4,11 @@ cmdname=${0##*/}
 
 helpmsg () {
     echo "Brief:"
-    echo "    git commit and push with [comment]"
+    echo "    1. git push"
+    echo "    2. git add all, commit with [comment], then push"
     echo "Usage:"
-    echo "    $cmdname [comment]"
+    echo "    1. $cmdname"
+    echo "    2. $cmdname [comment]"
     echo "Try again"
     echo ""
 }
@@ -34,26 +36,26 @@ makesure() {
 
 # error 1: git comment is a must
 if [[ $# -lt 1 ]]; then
-    helpmsg
-    exit 1
+    echo "[lin-vim] git push on '$branch', path: '$PWD'"
+    git push
+else
+    comment="$@"
+
+    # error 2: not a git repository
+    if ! git status 1>/dev/null 2>&1; then
+        echo "error: git repository not exist"
+        helpmsg
+        exit 1
+    fi
+
+    branch=$(git status | head -n 1 | awk '{print $3}')
+    echo "[lin-vim] git push on '$branch', comment: '$comment', path: '$PWD'"
+    echo -n "[lin-vim] yes? "
+    makesure
+
+    cd $(gitroot)
+    git pull
+    git add -A .
+    git commit -m "$comment"
+    git push
 fi
-
-comment="$@"
-
-# error 2: not a git repository
-if ! git status 1>/dev/null 2>&1; then
-    echo "error: git repository not exist"
-    helpmsg
-    exit 1
-fi
-
-branch=$(git status | head -n 1 | awk '{print $3}')
-echo "[lin-vim] git push on '$branch', comment: '$comment', path: '$PWD'"
-echo -n "[lin-vim] yes? "
-makesure
-
-cd $(gitroot)
-git pull
-git add -A .
-git commit -m "$comment"
-git push
